// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl7Aq5IBN486g5JwiqOV-JHJsJwnG1Xx0',
    appId: '1:542301889339:android:07aab163434b2ab7888d1e',
    messagingSenderId: '542301889339',
    projectId: 'guardianlink-7c705',
    storageBucket: 'guardianlink-7c705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT-Ukqsw_8o4jQUXyCPtpkIMpvE3ZuQEI',
    appId: '1:542301889339:ios:92022804984b4abf888d1e',
    messagingSenderId: '542301889339',
    projectId: 'guardianlink-7c705',
    storageBucket: 'guardianlink-7c705.firebasestorage.app',
    iosBundleId: 'com.guardianlink.guardianLink',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaWd8mULZ9D3PF3bxIYlUxQqJSFUf07NU',
    appId: '1:542301889339:web:f2fb4ccaad70188e888d1e',
    messagingSenderId: '542301889339',
    projectId: 'guardianlink-7c705',
    authDomain: 'guardianlink-7c705.firebaseapp.com',
    storageBucket: 'guardianlink-7c705.firebasestorage.app',
    measurementId: 'G-MBGCV9E3HS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT-Ukqsw_8o4jQUXyCPtpkIMpvE3ZuQEI',
    appId: '1:542301889339:ios:92022804984b4abf888d1e',
    messagingSenderId: '542301889339',
    projectId: 'guardianlink-7c705',
    storageBucket: 'guardianlink-7c705.firebasestorage.app',
    iosBundleId: 'com.guardianlink.guardianLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaWd8mULZ9D3PF3bxIYlUxQqJSFUf07NU',
    appId: '1:542301889339:web:cf82b4e3f9ff33aa888d1e',
    messagingSenderId: '542301889339',
    projectId: 'guardianlink-7c705',
    authDomain: 'guardianlink-7c705.firebaseapp.com',
    storageBucket: 'guardianlink-7c705.firebasestorage.app',
    measurementId: 'G-2RXTE21QZ5',
  );

}